development:
   adapter: mysql
   encoding: utf8
   database: nycrestaurants
   username: root
   password:

test:
   adapter: mysql
   encoding: utf8
   database: nycrestaurants_test
   username: root
   password:
