development: &non_production_settings
  site_url: http://restaurant_map.local
  site_name: NYC Restaurants
  admin_email: michael@nuttnet.net
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.example.com
  site_name: Bort
  admin_email: bort@bort.com  
  
production:
  site_url: http://nycrestaurants.heroku.com
  site_name: NYC Restaurants
  admin_email: michael@nuttnet.net
